clc;clear all; close all;
load('variablesForNextPlot.mat')
[a_fitAluminum, sig_aAluminum, yyAluminum, chisqrAluminum] = ...
    linreg(x.two,y.two,dy.alumRange);
fprintf('Fit parameters:\n');

fprintf(' k = %0.3g +/- %0.3g \n',a_fitAluminum(1),sig_aAluminum(1));
fprintf(' B = %0.3g +/- %0.3g \n',a_fitAluminum(2),sig_aAluminum(2));
prettygraphMine(x.two,yyAluminum,x.two,y.two,dy.alumRange,...
    a_fitAluminum(1),a_fitAluminum(2),chisqrAluminum,figurePath,...
    'linearAluminumGraph');
%%
% 		fig1=figure(1); clf;           % Bring figure 1 window forward
% 		errorbar(x.two,y.two,dy.alumRange,'.');  % Graph data with error bars
% 		hold on;                  % Freeze the plot to add the fit
% 		plot(x.two,yyAluminum,'-');           % Plot the fit on same graph as data
% 		xlabel('ln(E)'); ylabel('ln(R(E))');
% 		title(['Aluminum \chi^2 = ',num2str(chisqrAluminum),'    N-M = ',num2str(7-2)]);
%                 set(gca, ...
%     'Box'         , 'off'     , ...
%     'TickDir'     , 'out'     , ...
%     'TickLength'  , [.02 .02] , ...
%     'XMinorTick'  , 'on'      , ...
%     'YMinorTick'  , 'on'      , ...
%     'YGrid'       , 'on'      , ...
%     'XColor'      , [.3 .3 .3], ...
%     'YColor'      , [.3 .3 .3], ...
%     'LineWidth'   , 1         );
%% plastic
[a_fitPlastic, sig_aPlastic, yyPlastic, chisqrPlastic] = ...
    linreg(x.plasTwo,y.plasTwo,dy.plasRange);
fprintf('Fit parameters:\n');

fprintf(' k = %0.3g +/- %0.3g \n',a_fitPlastic(1),sig_aPlastic(1));
fprintf(' B = %0.3g +/- %0.3g \n',a_fitPlastic(2),sig_aPlastic(2));
prettygraphMine(x.two,yyAluminum,x.two,y.two,dy.alumRange,...
    a_fitAluminum(1),a_fitAluminum(2),chisqrAluminum,figurePath,...
    'linearAluminumGraph');
%% 
% 		figure(2); clf;           % Bring figure 1 window forward
% 		errorbar(x.plasTwo,y.plasTwo,dy.plasRange,'.');  % Graph data with error bars
% 		hold on;                  % Freeze the plot to add the fit
% 		plot(x.plasTwo,yyPlastic,'-');           % Plot the fit on same graph as data
% 		xlabel('ln(E)'); ylabel('ln(R(E))');
% 		title(['Plastic \chi^2 = ',num2str(chisqrPlastic),'    N-M = ',num2str(7-2)]);
%         legend('y=mx+b','location','best');
%         set(gca, ...
%     'Box'         , 'off'     , ...
%     'TickDir'     , 'out'     , ...
%     'TickLength'  , [.02 .02] , ...
%     'XMinorTick'  , 'on'      , ...
%     'YMinorTick'  , 'on'      , ...
%     'YGrid'       , 'on'      , ...
%     'XColor'      , [.3 .3 .3], ...
%     'YColor'      , [.3 .3 .3], ...
%     'LineWidth'   , 1         );
%% functionprettygraphMine
% prettygraphMine(x.two,yyAluminum,x.two,y.two,dy.alumRange);