function otherSources(plotOf.OurErrorBarsAluminum,...
    plotOf.OurFitPlastic,plotOf.OurErrorBarsPlastic,...
    plotOf.OurFitAluminum,printTrueFalse,k.aluminum,B.aluminum,k.plastic,B.plastic)
[kinetic,csda] = importNISTdataNow('edatacsda_Range.txt',6, 86);
nist.Range = 23:30;
plotOf.NIST=plot(kinetic(nist.Range),...
    csda(nist.Range),'color','r');
%% Other Source
nist.energy = kinetic;
source.Other = .412*nist.energy.^(1.265 - ...
    0.0954*log(nist.energy));
plotOf.Other = plot(kinetic(nist.Range)...
    ,source.Other(nist.Range),'m');
%% Plot features
hLegend = legend([plotOf.OurFitAluminum,plotOf.OurFitPlastic,...
    plotOf.NIST,plotOf.Other],...
    sprintf('R(E)=%g E^{%g}\n',k.aluminum,B.aluminum),...
    sprintf('R(E)=%g E^{%g}\n',k.plastic,B.plastic),...
    'NIST','Other');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel], ...
    'FontName'   , 'AvantGarde');
set([ gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel,hLegend]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );
set([plotOf.OurFitAluminum,plotOf.OurFitPlastic,...
    plotOf.NIST,plotOf.Other], ...
    'LineWidth'       , 1.5          );
set([plotOf.OurErrorBarsAluminum,plotOf.OurErrorBarsPlastic], ...
    'LineWidth'       , 1.5          );
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
hold off;
% printTrueFalse=0;
if printTrueFalse == 1
    set(gcf, 'PaperPositionMode', 'auto');
    figurePath = ['/Users/kevin/SkyDrive/KTH Work/Period 3'...
        ' 2014/SH2008/Atomic Nucleus Revised/Figures/'];
    print('-depsc2',[figurePath sprintf('alum_plas_NIST_plot')])
end
output_args = 1;
end

